apiVersion: apps/v1
kind: Deployment
metadata:
  name: piorodemo
spec:
  spec:
    selector:
      matchLabels:
        app: piorodemo
  replicas: 3
  template:
    metadata:
      labels:
        app: piorodemo
      containers:
        - name: piorodemo
          image: 'gcr.io/find-seller-100100/pl.pioro.tutorial/piorodemo:0.0.1'
          ports:
            - containerPort: 8080

