apiVersion: v1
kind: Service
metadata:
  name: piorodemo-service
  labels:
    name: piorodemo-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: piorodemo
  type: LoadBalancer
